{
 "title": "Мониторинг сервера БД",
 "tags": [
  "system",
  "postgres"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "label": "Hostname:", "query": { "query": "label_values(nodename)" } },
   {
    "name": "hostname_node_exporter",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$hostname\"}, instance)"
    }
   },
   { "name": "hostname_db", "label": "Hostname databse: ", "query": { "query": "label_values(instance)" } },
   { "name": "datname", "label": "Database:", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  { "title": "ЦП", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Средняя загрузка (LA) 1/5/15",
   "type": "stat",
   "description": "Усреднённая загрузка системы за 1, 5, 15 минут",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$hostname_node_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{instance=\"$hostname_node_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{instance=\"$hostname_node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество ЦП",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{instance=\"$hostname_node_exporter\",mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование ЦП",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=\"$hostname_node_exporter\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "График использования ЦП",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{instance=\"$hostname_node_exporter\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU usage"
    }
   ]
  },
  { "title": "Оперативная память", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Всего RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$hostname_node_exporter\"}",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Всего SWAP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$hostname_node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "График использования RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$hostname_node_exporter\"} / 1024 / 1024 / 1024) - (node_memory_MemAvailable_bytes{instance=\"$hostname_node_exporter\"} / 1024 / 1024 / 1024)",
     "legendFormat": "RAM usage"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$hostname_node_exporter\"} / 1024 / 1024 / 1024) - (node_memory_SwapFree_bytes{instance=\"$hostname_node_exporter\"} / 1024 / 1024 / 1024)",
     "legendFormat": "SWAP usage"
    }
   ]
  },
  {
   "title": "Использование RAM",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$hostname_node_exporter\"}) - (node_memory_MemAvailable_bytes{instance=\"$hostname_node_exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование SWAP",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$hostname_node_exporter\"}) - (node_memory_SwapFree_bytes{instance=\"$hostname_node_exporter\"})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "Дисковое простратнство", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Всего памяти в разделе GB",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$hostname_node_exporter\",mountpoint!~\".*run.*\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{mountpoint}} ({{fstype}})"
    }
   ]
  },
  {
   "title": "Использование памяти GB",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$hostname_node_exporter\", mountpoint!~\".*run.*\"} / 1024 / 1024 / 1024) - (node_filesystem_avail_bytes{instance=\"$hostname_node_exporter\", mountpoint!~\".*run.*\"} / 1024 / 1024 / 1024)",
     "legendFormat": "{{mountpoint}} ({{fstype}})"
    }
   ]
  },
  {
   "title": "Использование памяти в %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=\"$hostname_node_exporter\",mountpoint!~\".*run.*\"} / node_filesystem_size_bytes{instance=\"$hostname_node_exporter\",mountpoint!~\".*run.*\"} * 100)",
     "legendFormat": "{{mountpoint}} ({{fstype}})"
    }
   ]
  },
  {
   "title": "График использования памяти",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$hostname_node_exporter\",device!~\"tmpfs\"} / 1024 / 1024 / 1024) - (node_filesystem_avail_bytes{instance=\"$hostname_node_exporter\"} / 1024 / 1024 / 1024)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Чтение/Запись диска", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Чтение",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$hostname_node_exporter\",device!~\"sr.*\",device!~\"dm.*\"}[1m])",
     "legendFormat": "{{device}}_recive"
    }
   ]
  },
  {
   "title": "Запись",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$hostname_node_exporter\",device!~\"sr.*\",device!~\"dm.*\"}[1m])",
     "legendFormat": "{{device}}_recive"
    }
   ]
  },
  {
   "title": "Чтение/Запись диска",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$hostname_node_exporter\",device!~\"sr.*\",device!~\"dm.*\"}[1m]) * -1",
     "legendFormat": "{{device}}_Чтение"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$hostname_node_exporter\",device!~\"sr.*\",device!~\"dm.*\"}[1m])",
     "legendFormat": "{{device}}_Запись"
    }
   ]
  },
  { "title": "Сеть", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Приём трафика",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$hostname_node_exporter\",device!~\"veth.*\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Передача трафика",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$hostname_node_exporter\",device!~\"veth.*\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Приём/Передача трафика",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$hostname_node_exporter\",device!~\"veth.*\"}[1m])",
     "legendFormat": "{{device}}_Приём"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$hostname_node_exporter\",device!~\"veth.*\"}[1m]) * -1",
     "legendFormat": "{{device}}_Передача"
    }
   ]
  },
  { "title": "База данных", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Версия Postgres",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_static{instance=\"$hostname_db\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Доступность БД",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Объем базы данных (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance=\"$hostname_db\", datname=\"$datname\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlock'и и конфликты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 9, "y": 45 },
   "targets": [
    {
     "expr": "pg_stat_database_deadlocks{instance=\"$hostname_db\", datname=\"$datname\"}",
     "legendFormat": "Deadlock'и"
    },
    {
     "expr": "pg_stat_database_conflicts{instance=\"$hostname_db\", datname=\"$datname\"}",
     "legendFormat": "Конфиликты"
    }
   ]
  },
  {
   "title": "Максимальное количество подключений",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_max_connections_max_connections{instance=\"common.sandox_db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущее количество подключений",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{instance=\"$hostname_db\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}