{
 "title": "Мониторинг сервера",
 "tags": [ "system" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Infrastructure", "query": { "query": "label_values(infrastructure)" } },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values({infrastructure=\"$Infrastructure\"},app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ЦП", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Средняя загрузка (LA) 1/5/15",
   "type": "stat",
   "description": "Усреднённая загрузка системы за 1, 5, 15 минут",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{app=\"$app\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{app=\"$app\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{app=\"$app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество ЦП",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{app=\"$app\",mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование ЦП",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{app=\"$app\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "График использования ЦП",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{app=\"$app\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "ЦП"
    }
   ]
  },
  { "title": "Оперативная память", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Всего RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{app=\"$app\"}",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Всего SWAP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{app=\"$app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "График использования RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{app=\"$app\"}) - (node_memory_MemAvailable_bytes{app=\"$app\"})",
     "legendFormat": "RAM"
    },
    {
     "expr": "node_memory_MemTotal_bytes{app=\"$app\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{app=\"$app\"} - node_memory_MemAvailable_bytes{app=\"$app\"}) + node_memory_Cached_bytes{app=\"$app\"}",
     "legendFormat": "RAM + Cache"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{app=\"$app\"}) - (node_memory_SwapFree_bytes{app=\"$app\"})",
     "legendFormat": "SWAP"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{app=\"$app\"}",
     "legendFormat": "SWAP Total"
    }
   ]
  },
  {
   "title": "Использование RAM",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{app=\"$app\"}) - (node_memory_MemAvailable_bytes{app=\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование SWAP",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{app=\"$app\"}) - (node_memory_SwapFree_bytes{app=\"$app\"})",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "Дисковое простратнство", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Всего памяти в разделе GB",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{app=\"$app\",mountpoint!~\".*run.*\"}",
     "legendFormat": "{{mountpoint}} ({{fstype}})"
    }
   ]
  },
  {
   "title": "Использование памяти GB",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{app=\"$app\", mountpoint!~\".*run.*\"}) - (node_filesystem_avail_bytes{app=\"$app\", mountpoint!~\".*run.*\"})",
     "legendFormat": "{{mountpoint}} ({{fstype}})"
    }
   ]
  },
  {
   "title": "Использование памяти в %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{app=\"$app\",mountpoint!~\".*run.*\"} / node_filesystem_size_bytes{app=\"$app\",mountpoint!~\".*run.*\"} * 100)",
     "legendFormat": "{{mountpoint}} ({{fstype}})"
    }
   ]
  },
  {
   "title": "График использования памяти",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{app=\"$app\",device!~\"tmpfs\"}) - (node_filesystem_avail_bytes{app=\"$app\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Чтение/Запись диска", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Чтение",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{app=\"$app\",device!~\"sr.*\",device!~\"dm.*\"}[1m])",
     "legendFormat": "{{device}}_recive"
    }
   ]
  },
  {
   "title": "Запись",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{app=\"$app\",device!~\"sr.*\",device!~\"dm.*\"}[1m])",
     "legendFormat": "{{device}}_recive"
    }
   ]
  },
  {
   "title": "Чтение/Запись диска",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{app=\"$app\",device!~\"sr.*\",device!~\"dm.*\"}[1m]) * -1",
     "legendFormat": "{{device}}_Чтение"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{app=\"$app\",device!~\"sr.*\",device!~\"dm.*\"}[1m])",
     "legendFormat": "{{device}}_Запись"
    }
   ]
  },
  { "title": "Сеть", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Приём трафика",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{app=\"$app\",device!~\"veth.*\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Передача трафика",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{app=\"$app\",device!~\"veth.*\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Приём/Передача трафика",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{app=\"$app\",device!~\"veth.*\"}[1m])",
     "legendFormat": "{{device}}_Приём"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{app=\"$app\",device!~\"veth.*\"}[1m]) * -1",
     "legendFormat": "{{device}}_Передача"
    }
   ]
  }
 ]
}